openapi: 3.0.3
info:
  title: Genxoft.dev api
  description: Personal home page api
  version: 1.0.1

servers:
  - url: http://localhost:8080/api
    description: localhost
  - url: https://genxoft.dev/api
    description: production
components:
  schemas:
    FcmSettings:
      type: object
      properties:
        token:
          type: string
        timezone:
          type: string
    Health:
      type: object
      properties:
        message:
          type: string
        version:
          type: string
        releaseId:
          type: string
paths:
  /health:
    get:
      description: Check service health
      responses:
        '200':
          description: Service health status
          content:
            application/health+json:
              schema:
                $ref: '#/components/schemas/Health'

  /fcm-token:
    post:
      description: Receive fcm token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FcmSettings'
      responses:
        '200':
          description: Returns nothing
        '400':
          description: Wrong request
          content:
            'text/plain': { }
